import React,{useEffect,useState}from'react';
import{posApi}from'../../services/apiService';
import{Users,RefreshCw,ClipboardCheck}from'lucide-react';
import{Button,FormField,TextInput,showToast,LoadingState}from'../../components/ui';
import{ShellPage,Section,StatTile}from'../../components/common/WorkspaceUI';

export default function PoolPortalPage(){
 const[attendance,setAttendance]=useState<any[]>([]);const[name,setName]=useState('');const[phone,setPhone]=useState('');const[count,setCount]=useState('1');const[notes,setNotes]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);
 const load=async()=>{try{setLoading(true);const response=await posApi.getPoolAttendance();setAttendance(response.data||[])}catch(e){showToast('error',e instanceof Error?e.message:'Unable to load pool attendance')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const today=attendance.filter(entry=>String(entry.createdAt||'').slice(0,10)===new Date().toISOString().slice(0,10));const visitors=today.reduce((sum,entry)=>sum+Number(entry.partySize||0),0);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const partySize=Number(count);if(!Number.isInteger(partySize)||partySize<1){showToast('error','Enter a whole number of visitors.');return}try{setBusy(true);await posApi.createPoolAttendance({visitorName:name,phone:phone||undefined,partySize,notes:notes||undefined});showToast('success','Pool attendance recorded');setName('');setPhone('');setCount('1');setNotes('');await load()}catch(error){showToast('error',error instanceof Error?error.message:'Unable to record attendance')}finally{setBusy(false)}};
 return <ShellPage eyebrow="POOL · ATTENDANCE" title="Pool attendance" subtitle="Record who entered the pool and the number of people in their party. No charges are collected here." actions={<Button variant="outline" size="sm" onClick={load}><RefreshCw size={14}/> Refresh</Button>}><div className="grid gap-4 sm:grid-cols-3"><StatTile label="Entries today" value={today.length} icon={ClipboardCheck}/><StatTile label="People today" value={visitors} icon={Users} accent/><StatTile label="Recent entries" value={attendance.length} note="Attendance records" icon={Users}/></div>{loading?<LoadingState/>:<div className="grid gap-6 lg:grid-cols-[420px_1fr]"><Section title="Record entry" subtitle="One record per visitor or group"><form onSubmit={submit} className="space-y-4 p-5"><FormField label="Visitor or group name" required><TextInput required value={name} onChange={e=>setName(e.target.value)} placeholder="Name of visitor or group lead"/></FormField><FormField label="Phone number"><TextInput value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Optional contact number"/></FormField><FormField label="Number of people" required><TextInput required type="number" min="1" step="1" value={count} onChange={e=>setCount(e.target.value)}/></FormField><FormField label="Notes"><TextInput value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional details"/></FormField><Button className="w-full" loading={busy}><ClipboardCheck size={14}/> Record attendance</Button></form></Section><Section title="Recent attendance" subtitle="Latest pool entries"><div className="divide-y divide-[#edf0ed]">{attendance.length===0?<div className="p-10 text-center text-xs text-[#899397]">No pool attendance has been recorded yet.</div>:attendance.slice(0,20).map(entry=><div key={entry.id} className="flex items-center gap-4 px-5 py-4"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#eaf5f6] text-[#2e7f8c]"><Users size={15}/></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-extrabold text-[#26363e]">{entry.visitorName}</div><div className="mt-1 text-[10px] text-[#899397]">{entry.phone||'No phone recorded'}{entry.notes?` · ${entry.notes}`:''}</div></div><div className="text-right"><strong className="text-xs text-[#20343e]">{entry.partySize} {Number(entry.partySize)===1?'person':'people'}</strong><div className="mt-1 text-[10px] text-[#899397]">{entry.createdAt?new Date(entry.createdAt).toLocaleString():'—'}</div></div></div>)}</div></Section></div>}</ShellPage>
}
