import React, { useEffect, useState } from 'react';
import { reservationsApi, staysApi, roomsApi } from '../../services/apiService';
import { LogIn, LogOut, RefreshCw, UserRound, BedDouble } from 'lucide-react';
import { Button, Modal, FormField, TextInput, SelectInput, showToast, LoadingState, statusBadge } from '../../components/ui';
import { ShellPage, Section, StatTile, Toolbar } from '../../components/common/WorkspaceUI';

const hotelBoundary = (value: unknown, hour: number) => new Date(`${String(value).slice(0, 10)}T${String(hour).padStart(2, '0')}:00:00.000Z`);
const isArrivalDue = (reservation: any, now = new Date()) => ['PENDING', 'CONFIRMED'].includes(String(reservation.status).toUpperCase()) && now >= hotelBoundary(reservation.checkInDate, 14) && now < hotelBoundary(reservation.checkOutDate, 12);

export const FrontDeskPage: React.FC = () => {
  const [stays, setStays] = useState<any[]>([]); const [arrivals, setArrivals] = useState<any[]>([]); const [rooms, setRooms] = useState<any[]>([]);
  const [q, setQ] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [action, setAction] = useState<{ type: 'in' | 'out'; row: any } | null>(null);
  const [form, setForm] = useState({ idVerified: true, idDocumentType: 'PASSPORT', idDocumentNumber: '', roomCondition: 'CLEAN', paymentMethod: 'CASH' });
  const load = async () => { try { setLoading(true); const [r, s, rm] = await Promise.all([reservationsApi.list({ search: q || undefined }), staysApi.getActiveStays(), roomsApi.getRooms()]); setArrivals((r.data || []).filter((reservation) => isArrivalDue(reservation))); setStays(s.data || []); setRooms(rm.data || []); } catch (e) { showToast('error', e instanceof Error ? e.message : 'Unable to load front desk'); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(() => void load(), 200); return () => clearTimeout(timer); }, [q]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!action) return; try { setBusy(true); if (action.type === 'in') await staysApi.checkIn({ reservationId: action.row.id, ...form }); else await staysApi.checkOut({ reservationId: action.row.reservationId || action.row.id, roomCondition: form.roomCondition, paymentMethod: form.paymentMethod }); showToast('success', action.type === 'in' ? 'Guest checked in' : 'Payment recorded and guest checked out'); setAction(null); void load(); } catch (e) { showToast('error', e instanceof Error ? e.message : 'Unable to complete operation'); } finally { setBusy(false); } };
  const departureDate = (stay: any) => stay.reservation?.checkOutDate;
  return <ShellPage eyebrow="RECEPTION · FRONT DESK" title="Front desk" subtitle="Arrivals, in-house guests and payment-safe departures." actions={<Button variant="outline" size="sm" onClick={load}><RefreshCw size={14} /> Refresh</Button>}>
    <div className="grid gap-4 sm:grid-cols-4"><StatTile label="Arrivals due" value={arrivals.length} icon={LogIn} accent /><StatTile label="In house" value={stays.length} icon={UserRound} /><StatTile label="Ready rooms" value={rooms.filter((room) => ['AVAILABLE', 'READY'].includes(room.status)).length} icon={BedDouble} /><StatTile label="Departures" value={stays.filter((stay) => String(departureDate(stay) || '').slice(0, 10) === new Date().toISOString().slice(0, 10)).length} icon={LogOut} /></div>
    <Section title="Arrival desk" subtitle="Due arrivals include late arrivals from prior nights. Check-in starts at 2:00 PM."><Toolbar search={q} onSearch={setQ} placeholder="Find a guest or reservation…" />{loading ? <LoadingState /> : arrivals.length === 0 ? <div className="p-10 text-center text-xs text-[#899397]">No arrivals are due.</div> : <div className="divide-y divide-[#edf0ed]">{arrivals.map((reservation) => <div key={reservation.id} className="flex items-center gap-4 px-5 py-4"><UserRound size={18} className="text-[#174b59]" /><div className="min-w-0 flex-1"><div className="text-xs font-extrabold">{reservation.guests?.[0]?.guest ? `${reservation.guests[0].guest.firstName} ${reservation.guests[0].guest.lastName}` : 'Guest'}</div><div className="mt-1 text-[10px] text-[#8a9598]">Room {reservation.room?.number || '—'} · checkout {new Date(reservation.checkOutDate).toLocaleDateString()} 12:00 PM</div></div><Button size="sm" onClick={() => { setForm({ ...form, idVerified: true }); setAction({ type: 'in', row: reservation }); }}><LogIn size={14} /> Check in</Button></div>)}</div>}</Section>
    <Section title="Guests in house" subtitle="Active stays and checkout actions."><div className="divide-y divide-[#edf0ed]">{loading ? <LoadingState /> : stays.length === 0 ? <div className="p-10 text-center text-xs text-[#899397]">No active stays.</div> : stays.map((stay) => <div key={stay.id} className="flex items-center gap-4 px-5 py-4"><div className="flex-1"><div className="text-xs font-extrabold">{stay.guest ? `${stay.guest.firstName} ${stay.guest.lastName}` : 'Guest'}</div><div className="mt-1 text-[10px] text-[#8a9598]">Room {stay.room?.number || '—'} · departure {departureDate(stay) ? new Date(departureDate(stay)).toLocaleDateString() : '—'} 12:00 PM · checked in by {stay.checkedInByUser?.name || '—'}</div></div>{statusBadge(stay.status || 'CHECKED_IN')}<Button size="sm" variant="outline" onClick={() => setAction({ type: 'out', row: stay })}><LogOut size={14} /> Check out</Button></div>)}</div></Section>
    <Modal open={!!action} onClose={() => setAction(null)} title={action?.type === 'in' ? 'Guest check-in' : 'Settle and check out'}><form onSubmit={submit} className="space-y-4">{action?.type === 'in' ? <><FormField label="ID document type"><SelectInput value={form.idDocumentType} onChange={(e) => setForm({ ...form, idDocumentType: e.target.value })}><option>PASSPORT</option><option>NATIONAL_ID</option><option>DRIVERS_LICENSE</option></SelectInput></FormField><FormField label="ID document number"><TextInput value={form.idDocumentNumber} onChange={(e) => setForm({ ...form, idDocumentNumber: e.target.value })} /></FormField></> : <><div className="rounded-xl bg-[#f7f8f6] p-3 text-xs text-[#667278]">The selected method records the exact outstanding folio balance before checkout. A guest credit must be refunded first.</div><FormField label="Room condition"><SelectInput value={form.roomCondition} onChange={(e) => setForm({ ...form, roomCondition: e.target.value })}><option value="CLEAN">Clean</option><option value="DIRTY">Needs cleaning</option><option value="DAMAGED">Damaged</option></SelectInput></FormField><FormField label="Settlement method"><SelectInput value={form.paymentMethod} onChange={(e) => setForm({ ...form, paymentMethod: e.target.value })}><option>CASH</option><option>CARD</option><option>MOBILE_MONEY</option><option>BANK_TRANSFER</option></SelectInput></FormField></>}<div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setAction(null)}>Cancel</Button><Button type="submit" loading={busy}>{action?.type === 'in' ? 'Confirm check-in' : 'Settle & check out'}</Button></div></form></Modal>
  </ShellPage>;
};
export default FrontDeskPage;
