// ============================================
// NS LUXURY VILLA — Reception Report Page
// Real-time Front Desk Financial, MoMo, Booking & Expense Operations
// ============================================

import React, { useEffect, useState, useCallback, useMemo } from 'react';
import { reportsApi } from '../../services/apiService';
import { useAuthStore } from '../../stores/authStore';
import { useThemeStore } from '../../stores/themeStore';
import { formatCurrency, formatUserGreeting } from '@nslv/shared';
import {
  Smartphone,
  Banknote,
  Users,
  BedDouble,
  Receipt,
  Wallet,
  RefreshCw,
  Printer,
  FileSpreadsheet,
  Calendar,
  Layers,
  ArrowDownRight,
  ArrowUpRight,
  TrendingUp,
  CreditCard,
  Building2,
  CheckCircle2,
  Phone,
  UserRound,
  FileText,
  Clock,
  DollarSign,
  ChevronRight,
  ShieldAlert,
} from 'lucide-react';
import { Button, LoadingState, showToast, statusBadge } from '../../components/ui';
import { ShellPage, Section, StatTile } from '../../components/common/WorkspaceUI';

type PeriodMode = 'today' | 'yesterday' | 'week' | 'month' | 'custom';

export default function ReceptionReportPage() {
  const user = useAuthStore((s) => s.user);
  const { theme } = useThemeStore();
  const villaName = theme?.villaName || 'NS Luxury Villa';
  const greeting = formatUserGreeting(user);

  const todayStr = useMemo(() => new Date().toISOString().slice(0, 10), []);
  const [mode, setMode] = useState<PeriodMode>('today');
  const [customStart, setCustomStart] = useState(todayStr);
  const [customEnd, setCustomEnd] = useState(todayStr);
  const [activeTab, setActiveTab] = useState<'payments' | 'categories' | 'expenses' | 'reconciliation'>('payments');

  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  // Compute effective date bounds
  const { startDate, endDate, periodTitle } = useMemo(() => {
    if (mode === 'today') {
      return {
        startDate: todayStr,
        endDate: todayStr,
        periodTitle: `Today's Shift (${new Date().toLocaleDateString(undefined, { weekday: 'long', month: 'short', day: 'numeric', year: 'numeric' })})`,
      };
    }
    if (mode === 'yesterday') {
      const y = new Date();
      y.setDate(y.getDate() - 1);
      const yStr = y.toISOString().slice(0, 10);
      return {
        startDate: yStr,
        endDate: yStr,
        periodTitle: `Yesterday's Shift (${y.toLocaleDateString(undefined, { weekday: 'long', month: 'short', day: 'numeric', year: 'numeric' })})`,
      };
    }
    if (mode === 'week') {
      const now = new Date();
      const d = now.getDay();
      const diffToMonday = d === 0 ? -6 : 1 - d;
      const monday = new Date(now);
      monday.setDate(now.getDate() + diffToMonday);
      const sunday = new Date(monday);
      sunday.setDate(monday.getDate() + 6);
      const sStr = monday.toISOString().slice(0, 10);
      const eStr = sunday.toISOString().slice(0, 10);
      return {
        startDate: sStr,
        endDate: eStr,
        periodTitle: `This Week (${sStr} to ${eStr})`,
      };
    }
    if (mode === 'month') {
      const now = new Date();
      const first = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10);
      const last = new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().slice(0, 10);
      const monthName = now.toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
      return {
        startDate: first,
        endDate: last,
        periodTitle: `Month of ${monthName}`,
      };
    }
    return {
      startDate: customStart,
      endDate: customEnd,
      periodTitle: `Custom Period (${customStart} to ${customEnd})`,
    };
  }, [mode, todayStr, customStart, customEnd]);

  const load = useCallback(async () => {
    try {
      setLoading(true);
      const res = await reportsApi.getReceptionReport(startDate, endDate);
      setData(res.data || null);
    } catch (e) {
      showToast('error', e instanceof Error ? e.message : 'Unable to generate reception report');
    } finally {
      setLoading(false);
    }
  }, [startDate, endDate]);

  useEffect(() => {
    void load();
  }, [load]);

  const handlePrint = () => {
    window.print();
  };

  const handleExportCSV = () => {
    if (!data) return;
    const fin = data.financialSummary || {};
    const bkg = data.bookingSummary || {};
    const exp = data.expensesSummary || {};
    const rec = data.cashReconciliation || {};

    const rows: string[][] = [
      [`${villaName} — Reception Shift & Operations Report`],
      [`Period: ${periodTitle}`, `Generated At: ${new Date().toLocaleString()}`, `Generated By: ${user?.firstName || 'Staff'} ${user?.lastName || ''}`],
      [],
      ['=== 1. FINANCIAL COLLECTIONS SUMMARY ==='],
      ['Payment Method', 'Amount (GHS)', 'Transactions Count'],
      ['Mobile Money (MoMo)', String(fin.momo?.totalAmount || 0), String(fin.momo?.count || 0)],
      ['Cash at Reception', String(fin.cash?.totalAmount || 0), String(fin.cash?.count || 0)],
      ['Card Payments', String(fin.card?.totalAmount || 0), String(fin.card?.count || 0)],
      ['Bank Transfer', String(fin.bankTransfer?.totalAmount || 0), String(fin.bankTransfer?.count || 0)],
      ['Total Gross Collections', String(fin.totalCollections || 0)],
      ['Refunds Paid', String(fin.totalRefunds || 0)],
      ['Net Collections', String(fin.netCollections || 0)],
      [],
      ['=== 2. ROOM BOOKINGS & CATEGORY BREAKDOWN ==='],
      ['Room Category', 'Base Rate (GHS)', 'Bookings Count', 'Room Nights', 'Adults', 'Children', 'Total People', 'Total Revenue (GHS)', 'Deposit Paid (GHS)', 'Rooms Used'],
    ];

    for (const cat of bkg.categories || []) {
      rows.push([
        cat.categoryName,
        String(cat.basePrice || 0),
        String(cat.bookingsCount || 0),
        String(cat.roomNights || 0),
        String(cat.adults || 0),
        String(cat.children || 0),
        String(cat.totalPeople || 0),
        String(cat.totalRevenue || 0),
        String(cat.depositCollected || 0),
        cat.roomsList || '—',
      ]);
    }

    rows.push([]);
    rows.push(['Total Bookings', String(bkg.totalBookings || 0)]);
    rows.push(['Total People Accommodated', String(bkg.totalPeople || 0), `(${bkg.adults || 0} Adults, ${bkg.children || 0} Children)`]);
    rows.push(['Total Rooms Booked', String(bkg.totalRoomsBooked || 0)]);
    rows.push(['Total Room Nights', String(bkg.totalRoomNights || 0)]);

    rows.push([]);
    rows.push(['=== 3. MONEY TAKEN FROM RECEPTION FOR EXPENSES ==='], ['Date', 'Time', 'Category', 'Description', 'Recipient', 'Receipt Ref', 'Amount (GHS)', 'Recorded By']);
    for (const out of exp.disbursementsList || []) {
      rows.push([
        out.date || '',
        out.time || '',
        out.category || '',
        `"${(out.description || '').replace(/"/g, '""')}"`,
        out.recipient || '',
        out.receiptRef || '',
        String(out.amount || 0),
        out.recordedBy || '',
      ]);
    }
    rows.push(['Total Reception Expenses Taken', '', '', '', '', '', String(exp.totalTakenForExpenses || 0)]);

    rows.push([]);
    rows.push(['=== 4. CASH FLOAT & DRAWER RECONCILIATION ===']);
    rows.push(['Opening Cash Float (+)', String(rec.openingCashFloat || 0)]);
    rows.push(['Cash Collections Received (+)', String(rec.cashCollectionsReceived || 0)]);
    rows.push(['Manual Inflows (+)', String(rec.manualInflows || 0)]);
    rows.push(['Money Taken for Expenses (-)', String(rec.moneyTakenForExpenses || 0)]);
    rows.push(['Cash Refunds Paid (-)', String(rec.cashRefundsPaid || 0)]);
    rows.push(['Cash Deposited to Bank (-)', String(rec.cashDepositedToBank || 0)]);
    rows.push(['Expected Cash at Hand (=)', String(rec.expectedCashAtHand || 0)]);

    const csvContent = rows.map((r) => r.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `Reception_Report_${startDate}_${endDate}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    showToast('success', 'Reception Report CSV downloaded');
  };

  const fin = data?.financialSummary || {};
  const bkg = data?.bookingSummary || {};
  const exp = data?.expensesSummary || {};
  const rec = data?.cashReconciliation || {};
  const ops = data?.operationalHighlights || {};

  return (
    <ShellPage
      eyebrow="RECEPTION · FRONT DESK REPORTING & AUDIT"
      title="Reception Shift & Operations Report"
      subtitle="Mobile money (MoMo), cash collections, bookings, room category analysis, expense payouts & shift cash balancing."
      actions={
        <div className="flex flex-wrap items-center gap-2">
          <Button variant="outline" size="sm" onClick={handlePrint} className="gap-1.5 shadow-sm">
            <Printer size={14} className="text-[#16a4d4]" /> Print Shift Report
          </Button>
          <Button variant="outline" size="sm" onClick={handleExportCSV} className="gap-1.5 shadow-sm">
            <FileSpreadsheet size={14} className="text-[#2d8a68]" /> Export CSV
          </Button>
          <Button variant="primary" size="sm" onClick={load} className="gap-1.5 shadow-sm">
            <RefreshCw size={14} /> Refresh
          </Button>
        </div>
      }
    >
      {/* ─── Printable Header (Only visible on print) ────────────────────────── */}
      <div className="hidden print:block mb-6 border-b border-black pb-4 text-center">
        <div className="text-xl font-extrabold tracking-tight">{villaName}</div>
        <div className="text-sm font-semibold uppercase tracking-wider text-slate-700">Official Reception & Front Desk Shift Report</div>
        <div className="mt-1 text-xs text-slate-600">
          Period: {periodTitle} · Date Generated: {new Date().toLocaleString()} · Cashier / Shift: {user?.firstName} {user?.lastName}
        </div>
      </div>

      {/* ─── Period Selector Bar ────────────────────────────────────────────── */}
      <div className="ns-card flex flex-wrap items-center justify-between gap-4 p-4 shadow-sm print:hidden">
        <div className="flex flex-wrap items-center gap-1.5">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 mr-1 flex items-center gap-1">
            <Calendar size={13} /> Period:
          </span>
          <button
            onClick={() => setMode('today')}
            className={`rounded-lg px-3 py-1.5 text-xs font-bold transition ${
              mode === 'today' ? 'bg-[#16a4d4] text-white shadow-sm' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
            }`}
          >
            Today's Shift
          </button>
          <button
            onClick={() => setMode('yesterday')}
            className={`rounded-lg px-3 py-1.5 text-xs font-bold transition ${
              mode === 'yesterday' ? 'bg-[#16a4d4] text-white shadow-sm' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
            }`}
          >
            Yesterday
          </button>
          <button
            onClick={() => setMode('week')}
            className={`rounded-lg px-3 py-1.5 text-xs font-bold transition ${
              mode === 'week' ? 'bg-[#16a4d4] text-white shadow-sm' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
            }`}
          >
            This Week
          </button>
          <button
            onClick={() => setMode('month')}
            className={`rounded-lg px-3 py-1.5 text-xs font-bold transition ${
              mode === 'month' ? 'bg-[#16a4d4] text-white shadow-sm' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
            }`}
          >
            This Month
          </button>
          <button
            onClick={() => setMode('custom')}
            className={`rounded-lg px-3 py-1.5 text-xs font-bold transition ${
              mode === 'custom' ? 'bg-[#16a4d4] text-white shadow-sm' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
            }`}
          >
            Custom Range
          </button>
        </div>

        {mode === 'custom' && (
          <div className="flex items-center gap-2 text-xs font-medium">
            <label className="text-slate-500">From:</label>
            <input
              type="date"
              value={customStart}
              onChange={(e) => setCustomStart(e.target.value)}
              className="rounded-lg border border-slate-300 px-2.5 py-1 text-xs focus:border-[#16a4d4] focus:outline-none"
            />
            <label className="text-slate-500">To:</label>
            <input
              type="date"
              value={customEnd}
              onChange={(e) => setCustomEnd(e.target.value)}
              className="rounded-lg border border-slate-300 px-2.5 py-1 text-xs focus:border-[#16a4d4] focus:outline-none"
            />
          </div>
        )}

        <div className="text-xs font-extrabold text-[#16a4d4] bg-[#eef7fa] px-3 py-1.5 rounded-lg">
          {periodTitle}
        </div>
      </div>

      {loading ? (
        <LoadingState />
      ) : !data ? (
        <div className="ns-card p-12 text-center text-slate-500">No report data found for this period.</div>
      ) : (
        <>
          {/* ─── Hero KPI Metric Cards ────────────────────────────────────────── */}
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
            {/* 1. Mobile Money (MoMo) */}
            <div className="ns-card relative overflow-hidden p-4.5 border-l-4 border-l-[#f1a83f] shadow-sm hover:shadow transition">
              <div className="flex items-center justify-between text-slate-500 mb-2">
                <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-500">Total MoMo</span>
                <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-amber-50 text-[#f1a83f]">
                  <Smartphone size={15} />
                </span>
              </div>
              <div className="text-xl font-extrabold text-slate-900 leading-tight">
                {formatCurrency(fin.momo?.totalAmount || 0)}
              </div>
              <div className="mt-1 flex items-center justify-between text-[10px] text-slate-500 font-semibold">
                <span>{fin.momo?.count || 0} Transactions</span>
                <span className="rounded bg-amber-100 text-amber-800 px-1 py-0.5 text-[9px] font-bold">MoMo</span>
              </div>
            </div>

            {/* 2. Cash Collected */}
            <div className="ns-card relative overflow-hidden p-4.5 border-l-4 border-l-[#2d8a68] shadow-sm hover:shadow transition">
              <div className="flex items-center justify-between text-slate-500 mb-2">
                <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-500">Total Cash Received</span>
                <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-emerald-50 text-[#2d8a68]">
                  <Banknote size={15} />
                </span>
              </div>
              <div className="text-xl font-extrabold text-slate-900 leading-tight">
                {formatCurrency(fin.cash?.totalAmount || 0)}
              </div>
              <div className="mt-1 flex items-center justify-between text-[10px] text-slate-500 font-semibold">
                <span>{fin.cash?.count || 0} Cash Receipts</span>
                <span className="rounded bg-emerald-100 text-emerald-800 px-1 py-0.5 text-[9px] font-bold">Cash Desk</span>
              </div>
            </div>

            {/* 3. People Booked (Headcount) */}
            <div className="ns-card relative overflow-hidden p-4.5 border-l-4 border-l-[#16a4d4] shadow-sm hover:shadow transition">
              <div className="flex items-center justify-between text-slate-500 mb-2">
                <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-500">People Booked</span>
                <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-cyan-50 text-[#16a4d4]">
                  <Users size={15} />
                </span>
              </div>
              <div className="text-xl font-extrabold text-slate-900 leading-tight">
                {bkg.totalPeople || 0} <span className="text-xs font-bold text-slate-500">guests</span>
              </div>
              <div className="mt-1 text-[10px] text-slate-500 font-semibold">
                {bkg.adults || 0} Adults · {bkg.children || 0} Children
              </div>
            </div>

            {/* 4. Rooms Booked & Categories */}
            <div className="ns-card relative overflow-hidden p-4.5 border-l-4 border-l-[#7c3aed] shadow-sm hover:shadow transition">
              <div className="flex items-center justify-between text-slate-500 mb-2">
                <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-500">Rooms Booked</span>
                <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-purple-50 text-[#7c3aed]">
                  <BedDouble size={15} />
                </span>
              </div>
              <div className="text-xl font-extrabold text-slate-900 leading-tight">
                {bkg.totalRoomsBooked || 0} <span className="text-xs font-bold text-slate-500">rooms</span>
              </div>
              <div className="mt-1 text-[10px] text-slate-500 font-semibold">
                {bkg.totalBookings || 0} Bookings · {bkg.categories?.length || 0} Categories
              </div>
            </div>

            {/* 5. Money Taken for Expenses */}
            <div className="ns-card relative overflow-hidden p-4.5 border-l-4 border-l-[#dc2626] shadow-sm hover:shadow transition">
              <div className="flex items-center justify-between text-slate-500 mb-2">
                <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-500">Expenses Taken</span>
                <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-rose-50 text-[#dc2626]">
                  <Receipt size={15} />
                </span>
              </div>
              <div className="text-xl font-extrabold text-[#dc2626] leading-tight">
                {formatCurrency(exp.totalTakenForExpenses || 0)}
              </div>
              <div className="mt-1 text-[10px] text-slate-500 font-semibold">
                {exp.disbursementsCount || 0} Outflow Disbursements
              </div>
            </div>

            {/* 6. Net Cash at Hand (Float Reconciliation) */}
            <div className="ns-card relative overflow-hidden p-4.5 border-l-4 border-l-[#0f766e] shadow-sm hover:shadow transition">
              <div className="flex items-center justify-between text-slate-500 mb-2">
                <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-500">Cash in Hand</span>
                <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-teal-50 text-[#0f766e]">
                  <Wallet size={15} />
                </span>
              </div>
              <div className="text-xl font-extrabold text-slate-900 leading-tight">
                {formatCurrency(rec.expectedCashAtHand || 0)}
              </div>
              <div className="mt-1 text-[10px] text-slate-500 font-semibold flex items-center gap-1">
                <CheckCircle2 size={11} className="text-teal-600" /> Shift Drawer Balanced
              </div>
            </div>
          </div>

          {/* ─── Interactive Navigation Tabs ──────────────────────────────────── */}
          <div className="flex items-center gap-2 border-b border-slate-200 pb-1 print:hidden">
            <button
              onClick={() => setActiveTab('payments')}
              className={`flex items-center gap-2 px-4 py-2.5 text-xs font-extrabold border-b-2 transition ${
                activeTab === 'payments'
                  ? 'border-[#16a4d4] text-[#16a4d4]'
                  : 'border-transparent text-slate-500 hover:text-slate-900'
              }`}
            >
              <Smartphone size={15} />
              <span>MoMo & Cash Payments ({fin.allPaymentRecords?.length || 0})</span>
            </button>

            <button
              onClick={() => setActiveTab('categories')}
              className={`flex items-center gap-2 px-4 py-2.5 text-xs font-extrabold border-b-2 transition ${
                activeTab === 'categories'
                  ? 'border-[#16a4d4] text-[#16a4d4]'
                  : 'border-transparent text-slate-500 hover:text-slate-900'
              }`}
            >
              <BedDouble size={15} />
              <span>Rooms & Categories ({bkg.categories?.length || 0})</span>
            </button>

            <button
              onClick={() => setActiveTab('expenses')}
              className={`flex items-center gap-2 px-4 py-2.5 text-xs font-extrabold border-b-2 transition ${
                activeTab === 'expenses'
                  ? 'border-[#16a4d4] text-[#16a4d4]'
                  : 'border-transparent text-slate-500 hover:text-slate-900'
              }`}
            >
              <Receipt size={15} />
              <span>Expenses Taken ({exp.disbursementsCount || 0})</span>
            </button>

            <button
              onClick={() => setActiveTab('reconciliation')}
              className={`flex items-center gap-2 px-4 py-2.5 text-xs font-extrabold border-b-2 transition ${
                activeTab === 'reconciliation'
                  ? 'border-[#16a4d4] text-[#16a4d4]'
                  : 'border-transparent text-slate-500 hover:text-slate-900'
              }`}
            >
              <Wallet size={15} />
              <span>Shift Cash Reconciliation</span>
            </button>
          </div>

          {/* ══════════════════════════════════════════════════════════════════════
              TAB 1: MOMO & PAYMENT COLLECTIONS LEDGER
          ══════════════════════════════════════════════════════════════════════ */}
          {(activeTab === 'payments' || typeof window === 'undefined') && (
            <div className="space-y-6">
              {/* Payment Methods Breakdown Bar */}
              <div className="grid gap-4 sm:grid-cols-4">
                <div className="ns-card p-4">
                  <div className="text-[11px] font-bold text-slate-500 uppercase">Mobile Money (MoMo)</div>
                  <div className="text-lg font-extrabold text-[#f1a83f] mt-1">{formatCurrency(fin.momo?.totalAmount || 0)}</div>
                  <div className="text-[10px] text-slate-500 mt-0.5">{fin.momo?.count || 0} transactions</div>
                </div>
                <div className="ns-card p-4">
                  <div className="text-[11px] font-bold text-slate-500 uppercase">Cash Collected</div>
                  <div className="text-lg font-extrabold text-[#2d8a68] mt-1">{formatCurrency(fin.cash?.totalAmount || 0)}</div>
                  <div className="text-[10px] text-slate-500 mt-0.5">{fin.cash?.count || 0} transactions</div>
                </div>
                <div className="ns-card p-4">
                  <div className="text-[11px] font-bold text-slate-500 uppercase">Card Payments</div>
                  <div className="text-lg font-extrabold text-[#16a4d4] mt-1">{formatCurrency(fin.card?.totalAmount || 0)}</div>
                  <div className="text-[10px] text-slate-500 mt-0.5">{fin.card?.count || 0} transactions</div>
                </div>
                <div className="ns-card p-4">
                  <div className="text-[11px] font-bold text-slate-500 uppercase">Bank Transfer</div>
                  <div className="text-lg font-extrabold text-[#7c3aed] mt-1">{formatCurrency(fin.bankTransfer?.totalAmount || 0)}</div>
                  <div className="text-[10px] text-slate-500 mt-0.5">{fin.bankTransfer?.count || 0} transactions</div>
                </div>
              </div>

              {/* Mobile Money (MoMo) Itemized Table */}
              <Section
                title={`Mobile Money (MoMo) Payments Ledger (${fin.momo?.transactions?.length || 0})`}
                subtitle="All mobile money payments collected at front desk with transaction reference and guest confirmation."
              >
                {(!fin.momo?.transactions || fin.momo.transactions.length === 0) ? (
                  <div className="p-8 text-center text-xs text-slate-400">No Mobile Money payments recorded in this period.</div>
                ) : (
                  <div className="overflow-x-auto">
                    <table className="w-full text-left text-xs">
                      <thead className="border-b border-slate-200 bg-slate-50/80 text-[10px] font-extrabold uppercase tracking-wider text-slate-600">
                        <tr>
                          <th className="px-4 py-3">Time</th>
                          <th className="px-4 py-3">Guest Name & Phone</th>
                          <th className="px-4 py-3">Room / Confirmation</th>
                          <th className="px-4 py-3">MoMo Reference / Note</th>
                          <th className="px-4 py-3">Processed By</th>
                          <th className="px-4 py-3 text-right">Amount</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-100">
                        {fin.momo.transactions.map((t: any) => (
                          <tr key={t.id} className="hover:bg-amber-50/30 transition">
                            <td className="px-4 py-3 text-slate-500 font-mono text-[11px]">
                              {new Date(t.processedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                            </td>
                            <td className="px-4 py-3">
                              <div className="font-extrabold text-slate-900">{t.guestName}</div>
                              <div className="text-[10px] text-slate-500 flex items-center gap-1 mt-0.5">
                                <Phone size={10} /> {t.phone}
                              </div>
                            </td>
                            <td className="px-4 py-3">
                              <div className="font-bold text-slate-800">{t.roomNumber}</div>
                              <div className="text-[10px] text-slate-500 font-mono">{t.confirmationNo}</div>
                            </td>
                            <td className="px-4 py-3">
                              <span className="rounded border border-amber-300 bg-amber-50 px-1.5 py-0.5 font-mono text-[10px] font-extrabold text-amber-900">
                                {t.reference}
                              </span>
                              <div className="text-[10px] text-slate-500 mt-0.5 truncate max-w-xs">{t.description}</div>
                            </td>
                            <td className="px-4 py-3 text-slate-600 font-semibold">{t.processedBy}</td>
                            <td className="px-4 py-3 text-right font-extrabold text-[#f1a83f] text-sm">
                              {formatCurrency(t.amount)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                      <tfoot className="border-t-2 border-slate-300 bg-slate-50 font-extrabold">
                        <tr>
                          <td colSpan={5} className="px-4 py-3 text-right uppercase text-[11px] text-slate-600">
                            Total MoMo Collected:
                          </td>
                          <td className="px-4 py-3 text-right text-[#f1a83f] text-sm">
                            {formatCurrency(fin.momo?.totalAmount || 0)}
                          </td>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                )}
              </Section>

              {/* Cash & Other Payments Ledger */}
              <Section
                title={`All Front Desk Payment Collections (${fin.allPaymentRecords?.length || 0})`}
                subtitle="Complete audit trail of all receipts across Cash, MoMo, Card, and Bank Transfer."
              >
                {(!fin.allPaymentRecords || fin.allPaymentRecords.length === 0) ? (
                  <div className="p-8 text-center text-xs text-slate-400">No payment records found.</div>
                ) : (
                  <div className="overflow-x-auto">
                    <table className="w-full text-left text-xs">
                      <thead className="border-b border-slate-200 bg-slate-50/80 text-[10px] font-extrabold uppercase tracking-wider text-slate-600">
                        <tr>
                          <th className="px-4 py-3">Date / Time</th>
                          <th className="px-4 py-3">Method</th>
                          <th className="px-4 py-3">Guest & Details</th>
                          <th className="px-4 py-3">Room / Confirmation</th>
                          <th className="px-4 py-3">Staff</th>
                          <th className="px-4 py-3 text-right">Amount</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-100">
                        {fin.allPaymentRecords.map((p: any) => (
                          <tr key={p.id} className="hover:bg-slate-50 transition">
                            <td className="px-4 py-3 text-slate-500 font-mono text-[11px]">
                              {new Date(p.processedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                            </td>
                            <td className="px-4 py-3">
                              <span
                                className={`rounded px-2 py-0.5 text-[9px] font-extrabold ${
                                  p.method === 'MOBILE_MONEY'
                                    ? 'bg-amber-100 text-amber-800'
                                    : p.method === 'CASH'
                                    ? 'bg-emerald-100 text-emerald-800'
                                    : p.method === 'CARD'
                                    ? 'bg-cyan-100 text-cyan-800'
                                    : 'bg-purple-100 text-purple-800'
                                }`}
                              >
                                {p.method}
                              </span>
                            </td>
                            <td className="px-4 py-3">
                              <div className="font-extrabold text-slate-900">{p.guestName}</div>
                              {p.reference !== '—' && (
                                <div className="text-[10px] font-mono text-slate-500">Ref: {p.reference}</div>
                              )}
                            </td>
                            <td className="px-4 py-3">
                              <div className="font-bold text-slate-800">{p.roomNumber}</div>
                              <div className="text-[10px] text-slate-500 font-mono">{p.confirmationNo}</div>
                            </td>
                            <td className="px-4 py-3 text-slate-600 font-semibold">{p.processedBy}</td>
                            <td className="px-4 py-3 text-right font-extrabold text-slate-900">
                              {formatCurrency(p.amount)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                      <tfoot className="border-t-2 border-slate-300 bg-slate-50 font-extrabold">
                        <tr>
                          <td colSpan={5} className="px-4 py-3 text-right uppercase text-[11px] text-slate-600">
                            Total Gross Collections:
                          </td>
                          <td className="px-4 py-3 text-right text-slate-900 text-sm">
                            {formatCurrency(fin.totalCollections || 0)}
                          </td>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                )}
              </Section>
            </div>
          )}

          {/* ══════════════════════════════════════════════════════════════════════
              TAB 2: ROOMS BOOKED & CATEGORY BREAKDOWN
          ══════════════════════════════════════════════════════════════════════ */}
          {(activeTab === 'categories' || typeof window === 'undefined') && (
            <div className="space-y-6">
              {/* Category Cards Summary */}
              <Section
                title="Room Category Breakdown"
                subtitle="Performance, people accommodated, room nights, and revenue by room type."
              >
                {(!bkg.categories || bkg.categories.length === 0) ? (
                  <div className="p-8 text-center text-xs text-slate-400">No rooms booked in this period.</div>
                ) : (
                  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                    {bkg.categories.map((cat: any) => (
                      <div key={cat.categoryName} className="ns-card p-5 border border-slate-200/80 shadow-sm space-y-3">
                        <div className="flex items-start justify-between">
                          <div>
                            <div className="text-sm font-extrabold text-slate-900">{cat.categoryName}</div>
                            <div className="text-[10px] font-semibold text-slate-500">Base Rate: {formatCurrency(cat.basePrice)}/night</div>
                          </div>
                          <span className="rounded-full bg-cyan-100 text-cyan-800 font-extrabold text-[10px] px-2 py-0.5">
                            {cat.percentageShare}% of bookings
                          </span>
                        </div>

                        <div className="grid grid-cols-3 gap-2 border-y border-slate-100 py-3 text-center">
                          <div>
                            <div className="text-[10px] font-bold text-slate-400 uppercase">Bookings</div>
                            <div className="text-base font-extrabold text-slate-800 mt-0.5">{cat.bookingsCount}</div>
                          </div>
                          <div>
                            <div className="text-[10px] font-bold text-slate-400 uppercase">Nights</div>
                            <div className="text-base font-extrabold text-slate-800 mt-0.5">{cat.roomNights}</div>
                          </div>
                          <div>
                            <div className="text-[10px] font-bold text-slate-400 uppercase">Guests</div>
                            <div className="text-base font-extrabold text-slate-800 mt-0.5">{cat.totalPeople}</div>
                          </div>
                        </div>

                        <div className="flex items-center justify-between text-xs pt-1">
                          <span className="font-semibold text-slate-500">Total Category Revenue:</span>
                          <span className="font-extrabold text-[#16a4d4] text-sm">{formatCurrency(cat.totalRevenue)}</span>
                        </div>
                        {cat.roomsList && (
                          <div className="text-[10px] text-slate-400 truncate">
                            Rooms: <span className="font-semibold text-slate-600">{cat.roomsList}</span>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </Section>

              {/* Bookings & Reservations List Table */}
              <Section
                title={`Bookings in Period (${bkg.bookingsList?.length || 0})`}
                subtitle="Comprehensive guest reservations, headcounts (adults + children), and room assignments."
              >
                {(!bkg.bookingsList || bkg.bookingsList.length === 0) ? (
                  <div className="p-8 text-center text-xs text-slate-400">No bookings in this period.</div>
                ) : (
                  <div className="overflow-x-auto">
                    <table className="w-full text-left text-xs">
                      <thead className="border-b border-slate-200 bg-slate-50/80 text-[10px] font-extrabold uppercase tracking-wider text-slate-600">
                        <tr>
                          <th className="px-4 py-3">Conf #</th>
                          <th className="px-4 py-3">Guest Name & Phone</th>
                          <th className="px-4 py-3">Room & Category</th>
                          <th className="px-4 py-3">Dates (Nights)</th>
                          <th className="px-4 py-3 text-center">People (A/C)</th>
                          <th className="px-4 py-3">Status</th>
                          <th className="px-4 py-3 text-right">Total Amount</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-100">
                        {bkg.bookingsList.map((b: any) => (
                          <tr key={b.id} className="hover:bg-slate-50 transition">
                            <td className="px-4 py-3 font-mono font-bold text-slate-700 text-[11px]">{b.confirmationNo}</td>
                            <td className="px-4 py-3">
                              <div className="font-extrabold text-slate-900">{b.guestName}</div>
                              <div className="text-[10px] text-slate-500 flex items-center gap-1">
                                <Phone size={10} /> {b.phone}
                              </div>
                            </td>
                            <td className="px-4 py-3">
                              <div className="font-extrabold text-slate-800">Room {b.roomNumber}</div>
                              <div className="text-[10px] text-slate-500 font-semibold">{b.categoryName}</div>
                            </td>
                            <td className="px-4 py-3">
                              <div className="font-semibold text-slate-800">
                                {b.checkInDate} → {b.checkOutDate}
                              </div>
                              <div className="text-[10px] text-slate-500 font-bold">{b.nights} {b.nights === 1 ? 'night' : 'nights'}</div>
                            </td>
                            <td className="px-4 py-3 text-center">
                              <span className="rounded-full bg-slate-100 px-2 py-0.5 font-extrabold text-slate-800 text-[10px]">
                                {b.totalPeople} ({b.adults}A / {b.children}C)
                              </span>
                            </td>
                            <td className="px-4 py-3">{statusBadge(b.status)}</td>
                            <td className="px-4 py-3 text-right font-extrabold text-slate-900">
                              {formatCurrency(b.totalAmount)}
                              {b.depositAmount > 0 && (
                                <div className="text-[10px] font-semibold text-emerald-600">
                                  Dep: {formatCurrency(b.depositAmount)}
                                </div>
                              )}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                      <tfoot className="border-t-2 border-slate-300 bg-slate-50 font-extrabold">
                        <tr>
                          <td colSpan={4} className="px-4 py-3 uppercase text-[11px] text-slate-600">
                            Total People Accommodated: {bkg.totalPeople || 0} ({bkg.adults || 0} Adults, {bkg.children || 0} Children)
                          </td>
                          <td className="px-4 py-3 text-center text-slate-800">{bkg.totalPeople || 0}</td>
                          <td className="px-4 py-3 text-right uppercase text-[11px] text-slate-600">Total Accrued:</td>
                          <td className="px-4 py-3 text-right text-slate-900 text-sm">
                            {formatCurrency(
                              (bkg.categories || []).reduce((sum: number, c: any) => sum + (c.totalRevenue || 0), 0)
                            )}
                          </td>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                )}
              </Section>
            </div>
          )}

          {/* ══════════════════════════════════════════════════════════════════════
              TAB 3: MONEY TAKEN FOR EXPENSES (RECEPTION OUTFLOWS)
          ══════════════════════════════════════════════════════════════════════ */}
          {(activeTab === 'expenses' || typeof window === 'undefined') && (
            <div className="space-y-6">
              {/* Expense Category Breakdown */}
              <div className="grid gap-4 sm:grid-cols-4">
                {(exp.byCategory || []).map((cat: any) => (
                  <div key={cat.category} className="ns-card p-4 border-l-4 border-l-rose-500">
                    <div className="text-[10px] font-extrabold uppercase tracking-wider text-slate-500 truncate">{cat.category}</div>
                    <div className="text-lg font-extrabold text-rose-600 mt-1">{formatCurrency(cat.amount)}</div>
                    <div className="text-[10px] text-slate-400 mt-0.5">{cat.percentage}% of reception payouts</div>
                  </div>
                ))}
              </div>

              {/* Itemized Cash Outflows List */}
              <Section
                title={`Itemized Money Taken for Expenses (${exp.disbursementsList?.length || 0})`}
                subtitle="Detailed record of cash payouts, petty cash disbursements, recipients, and purposes taken from reception."
              >
                {(!exp.disbursementsList || exp.disbursementsList.length === 0) ? (
                  <div className="p-8 text-center text-xs text-slate-400">No expense disbursements recorded in this period.</div>
                ) : (
                  <div className="overflow-x-auto">
                    <table className="w-full text-left text-xs">
                      <thead className="border-b border-slate-200 bg-slate-50/80 text-[10px] font-extrabold uppercase tracking-wider text-slate-600">
                        <tr>
                          <th className="px-4 py-3">Date / Time</th>
                          <th className="px-4 py-3">Category</th>
                          <th className="px-4 py-3">Purpose / Description</th>
                          <th className="px-4 py-3">Recipient</th>
                          <th className="px-4 py-3">Voucher / Receipt</th>
                          <th className="px-4 py-3">Staff Member</th>
                          <th className="px-4 py-3 text-right">Amount Taken</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-100">
                        {exp.disbursementsList.map((d: any) => (
                          <tr key={d.id} className="hover:bg-rose-50/30 transition">
                            <td className="px-4 py-3 font-mono text-slate-500 text-[11px]">
                              {d.date} {d.time}
                            </td>
                            <td className="px-4 py-3">
                              <span className="rounded bg-rose-100 text-rose-800 font-extrabold px-2 py-0.5 text-[9px] uppercase">
                                {d.category}
                              </span>
                            </td>
                            <td className="px-4 py-3 font-medium text-slate-900 max-w-sm">
                              {d.description}
                            </td>
                            <td className="px-4 py-3 text-slate-800 font-bold">{d.recipient}</td>
                            <td className="px-4 py-3 font-mono text-[10px] text-slate-500">{d.receiptRef}</td>
                            <td className="px-4 py-3 text-slate-600 font-semibold">{d.recordedBy}</td>
                            <td className="px-4 py-3 text-right font-extrabold text-rose-600 text-sm">
                              -{formatCurrency(d.amount)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                      <tfoot className="border-t-2 border-slate-300 bg-slate-50 font-extrabold">
                        <tr>
                          <td colSpan={6} className="px-4 py-3 text-right uppercase text-[11px] text-slate-600">
                            Total Money Taken from Reception:
                          </td>
                          <td className="px-4 py-3 text-right text-rose-600 text-sm">
                            -{formatCurrency(exp.totalTakenForExpenses || 0)}
                          </td>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                )}
              </Section>
            </div>
          )}

          {/* ══════════════════════════════════════════════════════════════════════
              TAB 4: SHIFT FLOAT & CASH DRAWER RECONCILIATION
          ══════════════════════════════════════════════════════════════════════ */}
          {(activeTab === 'reconciliation' || typeof window === 'undefined') && (
            <div className="space-y-6">
              <Section
                title="Reception Shift Float & Cash Drawer Reconciliation"
                subtitle="Complete formula balancing cash at hand, room revenue inflows, expense disbursements, and bank deposits."
              >
                <div className="grid gap-6 md:grid-cols-2">
                  {/* Balancing Math Ledger */}
                  <div className="ns-card p-6 border border-slate-200 space-y-4">
                    <div className="text-xs font-extrabold uppercase tracking-wider text-slate-500 border-b border-slate-100 pb-2">
                      Cash Reconciliation Ledger
                    </div>

                    <div className="space-y-2.5 text-xs">
                      <div className="flex items-center justify-between">
                        <span className="font-semibold text-slate-600">Starting Opening Float (+)</span>
                        <span className="font-mono font-extrabold text-slate-900">{formatCurrency(rec.openingCashFloat || 0)}</span>
                      </div>

                      <div className="flex items-center justify-between text-emerald-700 bg-emerald-50/50 p-2 rounded">
                        <span className="font-semibold">Cash Collections from Guests (+)</span>
                        <span className="font-mono font-extrabold">+{formatCurrency(rec.cashCollectionsReceived || 0)}</span>
                      </div>

                      {rec.manualInflows > 0 && (
                        <div className="flex items-center justify-between text-emerald-700 p-2 rounded">
                          <span className="font-semibold">Other Cash Inflows (+)</span>
                          <span className="font-mono font-extrabold">+{formatCurrency(rec.manualInflows)}</span>
                        </div>
                      )}

                      <div className="flex items-center justify-between text-rose-700 bg-rose-50/50 p-2 rounded">
                        <span className="font-semibold">Money Taken for Expenses (-)</span>
                        <span className="font-mono font-extrabold">-{formatCurrency(rec.moneyTakenForExpenses || 0)}</span>
                      </div>

                      {rec.cashRefundsPaid > 0 && (
                        <div className="flex items-center justify-between text-rose-700 p-2 rounded">
                          <span className="font-semibold">Cash Refunds Issued (-)</span>
                          <span className="font-mono font-extrabold">-{formatCurrency(rec.cashRefundsPaid)}</span>
                        </div>
                      )}

                      {rec.cashDepositedToBank > 0 && (
                        <div className="flex items-center justify-between text-purple-700 p-2 rounded">
                          <span className="font-semibold">Cash Taken to Bank (-)</span>
                          <span className="font-mono font-extrabold">-{formatCurrency(rec.cashDepositedToBank)}</span>
                        </div>
                      )}

                      <div className="border-t-2 border-slate-300 pt-3 flex items-center justify-between text-sm">
                        <span className="font-extrabold text-slate-900 uppercase">Calculated Expected Cash at Hand (=)</span>
                        <span className="font-mono font-extrabold text-[#16a4d4] text-base">
                          {formatCurrency(rec.expectedCashAtHand || 0)}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Shift Handover Sign-off Box */}
                  <div className="ns-card p-6 border border-slate-200 space-y-4 flex flex-col justify-between">
                    <div>
                      <div className="text-xs font-extrabold uppercase tracking-wider text-slate-500 border-b border-slate-100 pb-2">
                        Shift Handover & Sign-off
                      </div>
                      <div className="mt-3 text-xs text-slate-600 space-y-2">
                        <p>
                          This shift summary certifies all cash, MoMo collections, and expense disbursements recorded during the specified period.
                        </p>
                        <div className="bg-slate-50 p-3 rounded-lg border border-slate-100 space-y-1 text-[11px]">
                          <div><span className="font-bold text-slate-700">Receptionist on Duty:</span> {user?.firstName} {user?.lastName} ({user?.username})</div>
                          <div><span className="font-bold text-slate-700">Check-ins in Period:</span> {ops.checkInsCount || 0}</div>
                          <div><span className="font-bold text-slate-700">Check-outs in Period:</span> {ops.checkOutsCount || 0}</div>
                          <div><span className="font-bold text-slate-700">Current In-House Guests:</span> {ops.activeStaysCount || 0}</div>
                        </div>
                      </div>
                    </div>

                    <div className="pt-4 border-t border-slate-200 grid grid-cols-2 gap-4 text-center">
                      <div className="border-t border-dashed border-slate-400 pt-2 text-[10px] text-slate-500">
                        Receptionist Signature
                      </div>
                      <div className="border-t border-dashed border-slate-400 pt-2 text-[10px] text-slate-500">
                        Manager / Auditor Signature
                      </div>
                    </div>
                  </div>
                </div>
              </Section>
            </div>
          )}
        </>
      )}
    </ShellPage>
  );
}
